name: Deploy Sanity Studio to Cloudflare Pages

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Build and deploy
    steps:
      - uses: actions/checkout@v3
      - name: Build
        run: |
            rm -rf node_modules
            npm cache clean --force
            npm install
            npm run build
      - name: Wait for Build Completion
        run: echo "Build completed."
      - name: Publish
        uses: cloudflare/wrangler-action@2.0.0
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: |
            pages deploy public --project-name=remix-sanity-cloudflare-actions